;;; rose-pine-dawn-theme.el --- Rosé Pine Dawn -*- lexical-binding: t; -*-

;;; Commentary:
;; A native Emacs theme using the Rosé Pine Dawn palette.  It intentionally has no package
;; dependencies and includes faces for the completion stack used here.

;;; Code:

(deftheme rose-pine-dawn
  "Rosé Pine Dawn.")

(let ((base           "#faf4ed")
      (surface        "#fffaf3")
      (overlay        "#f2e9e1")
      (muted          "#9893a5")
      (subtle         "#797593")
      (text           "#575279")
      (love           "#b4637a")
      (gold           "#ea9d34")
      (rose           "#d7827e")
      (pine           "#286983")
      (foam           "#56949f")
      (iris           "#907aa9")
      (highlight-low  "#f4ede8")
      (highlight-med  "#dfdad9")
      (highlight-high "#cecacd"))
  (custom-theme-set-faces
   'rose-pine-dawn

   ;; Core UI
   `(default ((t (:foreground ,text :background ,base))))
   `(cursor ((t (:foreground ,base :background ,text))))
   `(fringe ((t (:foreground ,muted :background ,base))))
   `(vertical-border ((t (:foreground ,highlight-high))))
   `(window-divider ((t (:foreground ,highlight-high))))
   `(window-divider-first-pixel ((t (:foreground ,highlight-high))))
   `(window-divider-last-pixel ((t (:foreground ,highlight-high))))
   `(internal-border ((t (:background ,highlight-high))))
   `(minibuffer-prompt ((t (:foreground ,pine :weight bold))))
   `(link ((t (:foreground ,iris :underline t))))
   `(link-visited ((t (:foreground ,rose :underline t))))
   `(shadow ((t (:foreground ,muted))))
   `(success ((t (:foreground ,pine :weight bold))))
   `(warning ((t (:foreground ,gold :weight bold))))
   `(error ((t (:foreground ,love :weight bold))))
   `(escape-glyph ((t (:foreground ,love))))
   `(homoglyph ((t (:foreground ,gold))))
   `(help-key-binding ((t (:foreground ,pine :background ,overlay :box (:line-width 1 :color ,highlight-high)))))

   ;; Selection and navigation
   `(region ((t (:foreground ,text :background ,highlight-med :extend t))))
   `(secondary-selection ((t (:foreground ,text :background ,overlay :extend t))))
   `(highlight ((t (:background ,highlight-low :extend t))))
   `(hl-line ((t (:background ,highlight-low :extend t))))
   `(match ((t (:foreground ,text :background ,highlight-med :weight bold))))
   `(isearch ((t (:foreground ,base :background ,gold :weight bold))))
   `(isearch-fail ((t (:foreground ,base :background ,love))))
   `(lazy-highlight ((t (:foreground ,text :background ,overlay))))
   `(query-replace ((t (:inherit isearch))))
   `(show-paren-match ((t (:foreground ,pine :background ,highlight-med :weight bold))))
   `(show-paren-mismatch ((t (:foreground ,base :background ,love :weight bold))))
   `(trailing-whitespace ((t (:background ,love))))

   ;; Mode line, tabs, and line numbers
   `(mode-line ((t (:foreground ,text :background ,overlay :box (:line-width 1 :color ,highlight-high)))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:foreground ,muted :background ,surface :box (:line-width 1 :color ,highlight-low)))))
   `(mode-line-buffer-id ((t (:foreground ,pine :weight bold))))
   `(header-line ((t (:foreground ,text :background ,surface :box (:line-width 1 :color ,highlight-high)))))
   `(line-number ((t (:foreground ,muted :background ,base))))
   `(line-number-current-line ((t (:foreground ,text :background ,highlight-low :weight bold))))
   `(line-number-major-tick ((t (:foreground ,iris :background ,base :weight bold))))
   `(line-number-minor-tick ((t (:foreground ,subtle :background ,base))))
   `(tab-bar ((t (:foreground ,muted :background ,surface))))
   `(tab-bar-tab ((t (:foreground ,text :background ,base :weight bold :box (:line-width 1 :color ,highlight-high)))))
   `(tab-bar-tab-inactive ((t (:foreground ,muted :background ,overlay))))

   ;; Font lock
   `(font-lock-builtin-face ((t (:foreground ,love))))
   `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,muted))))
   `(font-lock-constant-face ((t (:foreground ,gold))))
   `(font-lock-doc-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-doc-markup-face ((t (:foreground ,subtle))))
   `(font-lock-function-call-face ((t (:foreground ,pine))))
   `(font-lock-function-name-face ((t (:foreground ,pine))))
   `(font-lock-keyword-face ((t (:foreground ,iris :weight semi-bold))))
   `(font-lock-negation-char-face ((t (:foreground ,love :weight bold))))
   `(font-lock-number-face ((t (:foreground ,gold))))
   `(font-lock-operator-face ((t (:foreground ,subtle))))
   `(font-lock-preprocessor-face ((t (:foreground ,rose))))
   `(font-lock-property-name-face ((t (:foreground ,foam))))
   `(font-lock-property-use-face ((t (:foreground ,foam))))
   `(font-lock-punctuation-face ((t (:foreground ,subtle))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,love))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,iris))))
   `(font-lock-string-face ((t (:foreground ,gold))))
   `(font-lock-type-face ((t (:foreground ,foam))))
   `(font-lock-variable-name-face ((t (:foreground ,text))))
   `(font-lock-variable-use-face ((t (:foreground ,text))))
   `(font-lock-warning-face ((t (:foreground ,love :weight bold))))

   ;; Completion UI
   `(completions-annotations ((t (:foreground ,muted :slant italic))))
   `(completions-common-part ((t (:foreground ,pine :weight bold))))
   `(completions-first-difference ((t (:foreground ,iris :weight bold))))
   `(vertico-current ((t (:foreground ,text :background ,highlight-med :extend t))))
   `(vertico-group-title ((t (:foreground ,iris :weight bold))))
   `(vertico-group-separator ((t (:foreground ,highlight-high :strike-through t))))
   `(vertico-multiline ((t (:foreground ,muted))))
   `(vertico-quick1 ((t (:foreground ,love :background ,highlight-low :weight bold))))
   `(vertico-quick2 ((t (:foreground ,rose :background ,highlight-low :weight bold))))
   `(corfu-default ((t (:foreground ,text :background ,surface))))
   `(corfu-current ((t (:foreground ,text :background ,highlight-med))))
   `(corfu-border ((t (:background ,highlight-high))))
   `(corfu-bar ((t (:background ,muted))))
   `(corfu-annotations ((t (:foreground ,muted :slant italic))))
   `(corfu-deprecated ((t (:foreground ,muted :strike-through t))))
   `(corfu-popupinfo ((t (:foreground ,text :background ,surface))))
   `(corfu-quick1 ((t (:foreground ,love :weight bold))))
   `(corfu-quick2 ((t (:foreground ,rose :weight bold))))
   `(orderless-match-face-0 ((t (:foreground ,pine :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,iris :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,rose :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,gold :weight bold))))

   ;; Marginalia, Consult, and Embark
   `(marginalia-documentation ((t (:foreground ,muted :slant italic))))
   `(marginalia-key ((t (:foreground ,pine))))
   `(marginalia-type ((t (:foreground ,foam))))
   `(marginalia-function ((t (:foreground ,pine))))
   `(marginalia-symbol ((t (:foreground ,iris))))
   `(marginalia-value ((t (:foreground ,gold))))
   `(marginalia-string ((t (:foreground ,rose))))
   `(marginalia-date ((t (:foreground ,subtle))))
   `(marginalia-size ((t (:foreground ,subtle))))
   `(marginalia-file-owner ((t (:foreground ,muted))))
   `(marginalia-modified ((t (:foreground ,love))))
   `(consult-preview-line ((t (:background ,highlight-low :extend t))))
   `(consult-preview-match ((t (:foreground ,text :background ,highlight-med :weight bold))))
   `(consult-highlight-match ((t (:foreground ,pine :weight bold))))
   `(consult-highlight-mark ((t (:foreground ,iris :weight bold))))
   `(consult-narrow-indicator ((t (:foreground ,base :background ,iris :weight bold))))
   `(consult-key ((t (:foreground ,pine))))
   `(consult-line-number ((t (:foreground ,muted))))
   `(consult-grep-context ((t (:foreground ,muted))))
   `(embark-target ((t (:background ,highlight-low))))
   `(embark-keybinding ((t (:foreground ,pine))))
   `(embark-selected ((t (:foreground ,text :background ,highlight-med))))

   ;; Dired and buffers
   `(dired-directory ((t (:foreground ,pine :weight bold))))
   `(dired-symlink ((t (:foreground ,iris))))
   `(dired-header ((t (:foreground ,iris :weight bold))))
   `(dired-mark ((t (:foreground ,rose :weight bold))))
   `(dired-marked ((t (:foreground ,love :weight bold))))
   `(dired-flagged ((t (:foreground ,love :weight bold))))
   `(dired-broken-symlink ((t (:foreground ,base :background ,love))))
   `(buffer-menu-buffer ((t (:foreground ,pine :weight bold))))

   ;; Org
   `(org-document-title ((t (:foreground ,iris :weight bold :height 1.25))))
   `(org-document-info ((t (:foreground ,pine))))
   `(org-level-1 ((t (:foreground ,iris :weight bold :height 1.15))))
   `(org-level-2 ((t (:foreground ,pine :weight bold :height 1.10))))
   `(org-level-3 ((t (:foreground ,rose :weight bold))))
   `(org-level-4 ((t (:foreground ,gold :weight bold))))
   `(org-level-5 ((t (:foreground ,foam :weight bold))))
   `(org-level-6 ((t (:foreground ,love :weight bold))))
   `(org-block ((t (:foreground ,text :background ,surface :extend t))))
   `(org-block-begin-line ((t (:foreground ,muted :background ,overlay :extend t))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:foreground ,rose :background ,surface))))
   `(org-verbatim ((t (:foreground ,gold))))
   `(org-table ((t (:foreground ,pine))))
   `(org-link ((t (:foreground ,iris :underline t))))
   `(org-date ((t (:foreground ,foam :underline t))))
   `(org-todo ((t (:foreground ,love :weight bold))))
   `(org-done ((t (:foreground ,pine :weight bold))))
   `(org-headline-done ((t (:foreground ,muted))))
   `(org-checkbox ((t (:foreground ,pine :weight bold))))
   `(org-special-keyword ((t (:foreground ,muted))))
   `(org-meta-line ((t (:foreground ,muted :slant italic))))
   `(org-hide ((t (:foreground ,base))))

   ;; Diff, VC, diagnostics, and compilation
   `(diff-header ((t (:foreground ,subtle :background ,surface))))
   `(diff-file-header ((t (:foreground ,text :background ,overlay :weight bold))))
   `(diff-hunk-header ((t (:foreground ,iris :background ,highlight-low))))
   `(diff-added ((t (:foreground ,pine :background ,highlight-low))))
   `(diff-removed ((t (:foreground ,love :background ,highlight-low))))
   `(diff-changed ((t (:foreground ,gold :background ,highlight-low))))
   `(diff-refine-added ((t (:foreground ,base :background ,pine))))
   `(diff-refine-removed ((t (:foreground ,base :background ,love))))
   `(diff-refine-changed ((t (:foreground ,base :background ,gold))))
   `(flymake-error ((t (:underline (:style wave :color ,love)))))
   `(flymake-warning ((t (:underline (:style wave :color ,gold)))))
   `(flymake-note ((t (:underline (:style wave :color ,foam)))))
   `(compilation-error ((t (:foreground ,love))))
   `(compilation-warning ((t (:foreground ,gold))))
   `(compilation-info ((t (:foreground ,pine))))
   `(compilation-line-number ((t (:foreground ,iris))))
   `(compilation-column-number ((t (:foreground ,muted))))

   ;; Evil search/substitution
   `(evil-ex-info ((t (:foreground ,pine))))
   `(evil-ex-commands ((t (:foreground ,iris))))
   `(evil-ex-search ((t (:inherit isearch))))
   `(evil-ex-lazy-highlight ((t (:inherit lazy-highlight))))
   `(evil-ex-substitute-matches ((t (:foreground ,text :background ,highlight-med))))
   `(evil-ex-substitute-replacement ((t (:foreground ,love :underline t))))

   ;; Terminal and ANSI colors, matching Omarchy's generated terminal theme
   `(term-color-black ((t (:foreground ,base :background ,base))))
   `(term-color-red ((t (:foreground ,love :background ,love))))
   `(term-color-green ((t (:foreground ,pine :background ,pine))))
   `(term-color-yellow ((t (:foreground ,gold :background ,gold))))
   `(term-color-blue ((t (:foreground ,foam :background ,foam))))
   `(term-color-magenta ((t (:foreground ,iris :background ,iris))))
   `(term-color-cyan ((t (:foreground ,rose :background ,rose))))
   `(term-color-white ((t (:foreground ,text :background ,text))))
   `(ansi-color-black ((t (:foreground ,base :background ,base))))
   `(ansi-color-red ((t (:foreground ,love :background ,love))))
   `(ansi-color-green ((t (:foreground ,pine :background ,pine))))
   `(ansi-color-yellow ((t (:foreground ,gold :background ,gold))))
   `(ansi-color-blue ((t (:foreground ,foam :background ,foam))))
   `(ansi-color-magenta ((t (:foreground ,iris :background ,iris))))
   `(ansi-color-cyan ((t (:foreground ,rose :background ,rose))))
   `(ansi-color-white ((t (:foreground ,text :background ,text)))))

  (custom-theme-set-variables
   'rose-pine-dawn
   `(ansi-color-names-vector [,base ,love ,pine ,gold ,foam ,iris ,rose ,text])
   `(frame-background-mode 'light)))

;;;###autoload
(when (and load-file-name
           (boundp 'custom-theme-load-path))
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'rose-pine-dawn)

;;; rose-pine-dawn-theme.el ends here
