# Trigger Mode
TriggerMode=Hold
# Postprocess Menu Keys
SceneMenuKey=

[TriggerKey]
0=Shift+Alt_R
1=Alt+Shift_R

[CommandKeys]
0=Control_R

[AsrMenuKey]
0=F8

[PagePrevKeys]
0=Page_Up
1=KP_Page_Up

[PageNextKeys]
0=Next
1=KP_Next
